/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicBootstrapAdminsRouteImport } from './routes/api/public/bootstrap-admins'

const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBootstrapAdminsRoute =
  ApiPublicBootstrapAdminsRouteImport.update({
    id: '/api/public/bootstrap-admins',
    path: '/api/public/bootstrap-admins',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/catalogo': typeof CatalogoRoute
  '/api/public/bootstrap-admins': typeof ApiPublicBootstrapAdminsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/catalogo': typeof CatalogoRoute
  '/api/public/bootstrap-admins': typeof ApiPublicBootstrapAdminsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/catalogo': typeof CatalogoRoute
  '/api/public/bootstrap-admins': typeof ApiPublicBootstrapAdminsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/catalogo' | '/api/public/bootstrap-admins'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/catalogo' | '/api/public/bootstrap-admins'
  id: '__root__' | '/' | '/admin' | '/catalogo' | '/api/public/bootstrap-admins'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CatalogoRoute: typeof CatalogoRoute
  ApiPublicBootstrapAdminsRoute: typeof ApiPublicBootstrapAdminsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bootstrap-admins': {
      id: '/api/public/bootstrap-admins'
      path: '/api/public/bootstrap-admins'
      fullPath: '/api/public/bootstrap-admins'
      preLoaderRoute: typeof ApiPublicBootstrapAdminsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CatalogoRoute: CatalogoRoute,
  ApiPublicBootstrapAdminsRoute: ApiPublicBootstrapAdminsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
