/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicGenerateCategoryImagesRouteImport } from './routes/api/public/generate-category-images'
import { Route as ApiPublicBootstrapAdminsRouteImport } from './routes/api/public/bootstrap-admins'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGenerateCategoryImagesRoute =
  ApiPublicGenerateCategoryImagesRouteImport.update({
    id: '/api/public/generate-category-images',
    path: '/api/public/generate-category-images',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBootstrapAdminsRoute =
  ApiPublicBootstrapAdminsRouteImport.update({
    id: '/api/public/bootstrap-admins',
    path: '/api/public/bootstrap-admins',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/catalogo': typeof CatalogoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/public/bootstrap-admins': typeof ApiPublicBootstrapAdminsRoute
  '/api/public/generate-category-images': typeof ApiPublicGenerateCategoryImagesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/catalogo': typeof CatalogoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/public/bootstrap-admins': typeof ApiPublicBootstrapAdminsRoute
  '/api/public/generate-category-images': typeof ApiPublicGenerateCategoryImagesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/catalogo': typeof CatalogoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/public/bootstrap-admins': typeof ApiPublicBootstrapAdminsRoute
  '/api/public/generate-category-images': typeof ApiPublicGenerateCategoryImagesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/catalogo'
    | '/sitemap.xml'
    | '/api/public/bootstrap-admins'
    | '/api/public/generate-category-images'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/catalogo'
    | '/sitemap.xml'
    | '/api/public/bootstrap-admins'
    | '/api/public/generate-category-images'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/catalogo'
    | '/sitemap.xml'
    | '/api/public/bootstrap-admins'
    | '/api/public/generate-category-images'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CatalogoRoute: typeof CatalogoRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicBootstrapAdminsRoute: typeof ApiPublicBootstrapAdminsRoute
  ApiPublicGenerateCategoryImagesRoute: typeof ApiPublicGenerateCategoryImagesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/generate-category-images': {
      id: '/api/public/generate-category-images'
      path: '/api/public/generate-category-images'
      fullPath: '/api/public/generate-category-images'
      preLoaderRoute: typeof ApiPublicGenerateCategoryImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bootstrap-admins': {
      id: '/api/public/bootstrap-admins'
      path: '/api/public/bootstrap-admins'
      fullPath: '/api/public/bootstrap-admins'
      preLoaderRoute: typeof ApiPublicBootstrapAdminsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CatalogoRoute: CatalogoRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicBootstrapAdminsRoute: ApiPublicBootstrapAdminsRoute,
  ApiPublicGenerateCategoryImagesRoute: ApiPublicGenerateCategoryImagesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
