// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://syxhnmjmwxtlnsozrnwz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN5eGhubWptd3h0bG5zb3pybnd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODYzOTgxNjEsImV4cCI6MjEwMTk3NDE2MX0.0J5UorG9DpUC5ar6GrO2VmFDoovyRnwHJiIPIo42Cgc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});